FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# appuserを作成し、同時に主要グループを root (g=0) に指定する
RUN useradd -m -g root appuser

COPY ./python/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./python /app

# /app 以下の「グループ権限」にも書き込み権限（g+w）を与える
RUN chown -R appuser:root /app && \
    chmod -R 775 /app

USER appuser