services:
  frontend_youtube_free_anime:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.prod
    container_name: frontend_youtube_free_anime
    expose:
      - "3000"
    depends_on:
      - backend_youtube_free_anime
    restart: unless-stopped
    environment:
      NODE_ENV: production
    networks:
      - youtube_free_anime_network

  backend_youtube_free_anime:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.prod
    container_name: backend_youtube_free_anime
    expose:
      - "9000"
    depends_on:
      - db_youtube_free_anime
    restart: unless-stopped
    networks:
      - youtube_free_anime_network

  python_youtube_free_anime:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.prod
    container_name: python_youtube_free_anime
    working_dir: /app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - PYTHON_INTERNAL_API_TOKEN=${PYTHON_INTERNAL_API_TOKEN}
      - LARAVEL_API_URL=${LARAVEL_API_URL}
    depends_on:
      - db_youtube_free_anime
      - backend_youtube_free_anime

    tty: true
    restart: unless-stopped
    networks:
      - youtube_free_anime_network

  db_youtube_free_anime:
    image: postgres:16
    container_name: db_youtube_free_anime
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_youtube_free_anime_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432"
    restart: unless-stopped
    networks:
      - youtube_free_anime_network

  nginx_youtube_free_anime:
    image: nginx:1.29
    container_name: nginx_youtube_free_anime
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/prod/default.conf:/etc/nginx/templates/default.conf.template
      - ./logs/nginx:/var/log/nginx/daily
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
    environment:
      - CSP_SCRIPT_SRC='unsafe-inline'
      - NGINX_ENVSUBST_FILTER=CSP_SCRIPT_SRC
    depends_on:
      - frontend_youtube_free_anime
      - backend_youtube_free_anime
    restart: unless-stopped
    networks:
      - youtube_free_anime_network

  certbot_youtube_free_anime:
    image: certbot/certbot:latest
    container_name: certbot_youtube_free_anime
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
    # 12日ごとに自動で更新チェックを走らせる設定
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12d; done;'"
    networks:
      - youtube_free_anime_network

  ofelia_youtube_free_anime:
    image: mcuadros/ofelia:latest
    container_name: ofelia_youtube_free_anime
    depends_on:
      - python_youtube_free_anime
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      # --------------------------------------------------
      # データ取得
      # --------------------------------------------------
      ofelia.job-exec.job_file_a.schedule: "@every 8h"
      ofelia.job-exec.job_file_a.container: "python_youtube_free_anime"
      ofelia.job-exec.job_file_a.command: "python main.py"

      # --------------------------------------------------
      # 論理削除
      # --------------------------------------------------
      ofelia.job-exec.job_file_b.schedule: "@every 24h"
      ofelia.job-exec.job_file_b.container: "python_youtube_free_anime"
      ofelia.job-exec.job_file_b.command: "python /api/post_soft_delete.py"

    networks:
      - youtube_free_anime_network

volumes:
  db_youtube_free_anime_data:
  certbot_etc:
  certbot_var:

networks:
  youtube_free_anime_network:
    driver: bridge